### ISSUE TITLE
Update the code

### ISSUE THREAD

**Issue by irshadsyedx** [dankgrinder/dankgrinder#1]
**Expected behavior**
The behavior you expected

**Actual behavior**
What actually happened

**Steps to reproduce**
How the problem can be reproduced from a clean installation

**Logs**
If relevant, paste any errors or other logs here.

**Environment**
OS: e.g. MacOS 10.14.2, Windows, Ubuntu 20.04
Dank Grinder version: e.g. 1.4.12
Config: e.g.
```json
{
  "token": "thisisausertoken",
  "channel_id": "123456789",
  "user_id": "123456789",
  "enable": {
    "fish": true,
    "hunt": true
  },
  "response_delay": 0,
  "command_delay": 4000,
  "typing_duration": 500,
  "postmeme": [
    "f",
    "r",
    "i",
    "c",
    "k"
  ],
  "global_events": [
    **"krampus is a nerd",
    "whoville sucks",
    "build snowman",
    "make snow angel",
    "frick off",
    "happy holidays",
    "throw snowball",
    "push",
    "I've been a very good kid",
    "gimme gimme"**
  ],
  "search": [
    **"mistletoe",
    "christmas tree",
    "christmas card",
    "advent calendar"**
  ],
  "balance_check": {
    "enable": false,
    "username": ""
  },
  "auto_buy": {
    "fishing_pole": true,
    "hunting_rifle": true,
    "laptop": true
  }
}
```

**Additional comments**
Any other information that might be helpful but does not fit in the above categories.

PLS change the bolded part

**Comment by OsOmE1** [comment]
@irshadsyedx, please use the issue format and or make clear what you mean. "PLS change the bolded part" doesn't say a lot

**Comment by dankgrinder** [comment]
This is not a proper bug report. If you did actually find a bug please fill out all the headers properly, this is just an unedited template.
