### ISSUE TITLE
Rigging some commands

### ISSUE THREAD

**Issue by Zyzy69** [dankgrinder/dankgrinder#10]
Is there ANY way to change or predict the outcome of certain commands like "pls howgay" "pls simprate" or any other rate command that has a randomized chance of giving you a percentage, so for example I want to be able to get a high % of howgay at some certain times when I use the "pls howgay" command. Is there any way to predict or change the outcome?

**Comment by Zyzy69** [comment]
@dankgrinder can you respond please?

**Comment by Official-Darkn** [comment]
> @dankgrinder can you respond please?

Be patient for a response. People live in different time zones and need to sleep. So expect a response within 1-12 more hours.
**Why would he sleep for that long???**
He wouldn't sleep for that long but he has real life stuff to do aswell which can takes up to just minutes to hours and he just doesn't have to focus on a fucking bot autofarm

**Comment by Official-Darkn** [comment]
> Is there ANY way to change or predict the outcome of certain commands like "pls howgay" "pls simprate" or any other rate command that has a randomized chance of giving you a percentage, so for example I want to be able to get a high % of howgay at some certain times when I use the "pls howgay" command. Is there any way to predict or change the outcome?

No, there isn't. It's always random, so no.

**Comment by dankgrinder** [comment]
No, and this is not a feature that fits within the intended purpose of Dank Grinder.
