### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SoulHunter287** [dankgrinder/dankgrinder#123]
![IMG_20220421_133820](https://user-images.githubusercontent.com/81796062/164409729-5b4e19b1-514a-4ce3-93df-296d7f01aeab.jpg)
@Gold512

Umm the account has permission to send message and is not asking for verification and ip is also not blocked any idea why is it not working

**Comment by Gold512** [comment]
discord is sending 404 errors for some reason, no idea why some people say clicking buttons causes this but they were unsure as well. If i am free i might look into it if i can

**Comment by SoulHunter287** [comment]
Alright thanks 
And can u add button support to custom commands like it will send a command sleep for 1 second and then click the button specified

**Comment by SoulHunter287** [comment]
@Gold512
