### ISSUE TITLE
Auto Tidepod feature out of date

### ISSUE THREAD

**Issue by VenomRaiden** [dankgrinder/dankgrinder#127]
**Description**  
Describe what feature you will implement/modify
Auto Tidepod
**Affected components**  
What components of the application will be affected by this?
pls tidepod command
**Additional comments**  
Any other information that might be helpful but does not fit in the above categories.
Due to some update now u have to select confirm to use tidepods but the bot doesnt have that feature

**Comment by iDevYoyo** [comment]
did you found a solution?
