### ISSUE TITLE
Giving balances to main

### ISSUE THREAD

**Issue by tar420** [dankgrinder/dankgrinder#14]
I am currently running 4 acc's and 1 of them being my main, I had the intent to farm alot of money, send it to my main and coin bomb all my friends servers for some activity and interest but even though i do the custom command right. The command is not working because the application does not @ the user so i can not transfer all my coins on my alts to my main... any resolution for this  ?

**Comment by ihavezerohealth** [comment]
you need to set up the custom command with the userID.
for example, instead of saying @username#1621

you would say <@USERIDHERE>
you get someone's userid by enabling developer mode in discord, right-clicking on someone's name and clicking 'Copy ID'

**Comment by tar420** [comment]
oh sweet I tried it like this already :
"pls give @exampleID all"

do I have to use the <> brackets as-well when doing this ?

**Comment by ihavezerohealth** [comment]
yeah, the format is this:
<@userid>

**Comment by tar420** [comment]
thank you so much, cant believe i didnt think of this. i tried the ID before hand but without the <> and it wasnt working.
You saved me alot of time xD 
have a great day!

**Comment by ihavezerohealth** [comment]
no worries, be sure to join the discord server for future help!

**Comment by tar420** [comment]
Just realised that you need to confirm the transaction to be able to share
coins. I will join the discord and find a solution for this. Hopefully
someone understands this better than me xd
