### ISSUE TITLE
Editable pls bal cooldown

### ISSUE THREAD

**Issue by Explsn** [dankgrinder/dankgrinder#16]
**If I missed some way to pull this off with the current bot, I would appreciate an explanation on how to do it**
This seems useless but hear me out. I created a bot which gambles up to 10mil, and then shares 5 mil to another account. The problem is it will only share if it checked the bal with pls bal, which is on a huge cooldown and blocks a few gamble runs. 
Up to 7-8 empty runs, while my wallet is on 10 mil, resulting in a loss of money. It would be a nice improvement to make the balance features cooldown editable.

**Comment by dankgrinder** [comment]
It was a deliberate decision to prevent some unstable situations, but what you're saying makes sense. I was about to release 0.9.2, but I guess I'm implementing this now. Thanks for the suggestion

**Comment by dankgrinder** [comment]
https://github.com/dankgrinder/dankgrinder/releases/tag/0.9.2 :)
