### ISSUE TITLE
Add auto-use horseshoe

### ISSUE THREAD

**Issue by Official-Darkn** [dankgrinder/dankgrinder#17]
### The Horseshoe item in Dank Memer allows you to have an increase luck in using normal command such as fish, postmemes, hunt, beg, gamble, and etc.
With it being automatically used when it breaks you can constantly get more money.

**Comment by cluckingcluck** [comment]
use custom commands to buy horseshoe, as you don't need to actually use it. it's active automatically.
![image](https://user-images.githubusercontent.com/80233084/110266781-65c04c80-7f73-11eb-869b-3e4f3228ad19.png)

**Comment by Official-Darkn** [comment]
> use custom commands to buy horseshoe, as you don't need to actually use it. it's active automatically.
> ![image](https://user-images.githubusercontent.com/80233084/110266781-65c04c80-7f73-11eb-869b-3e4f3228ad19.png)
> 
> example ^^

Ah, I did not know that.

**Comment by Official-Darkn** [comment]
> use custom commands to buy horseshoe, as you don't need to actually use it. it's active automatically.
> ![image](https://user-images.githubusercontent.com/80233084/110266781-65c04c80-7f73-11eb-869b-3e4f3228ad19.png)
> 
> example ^^

Ah, I did not know that. Thanks!
