### ISSUE TITLE
Add allow all searches for auto pls search

### ISSUE THREAD

**Issue by PangwenE** [dankgrinder/dankgrinder#19]
I dont ssee the point in limiting it, and it would have you profit a whole lot more

**Comment by PangwenE** [comment]
i now know that there is more of a chance of dying iwth infinite searches, but for the people who wanna be risky still.

**Comment by ihavezerohealth** [comment]
you can just add them yourself and set a custom command to buy lifesavers for you

**Comment by dankgrinder** [comment]
It would be impractical to allow all searches because of the much higher chance of death. Moreover you can just add all searches you want in the config.
