### ISSUE TITLE
Autoblackjack Isn't Working

### ISSUE THREAD

**Issue by Ixyk-Wolf** [dankgrinder/dankgrinder#21]
**Expected behavior**
The bot to automatically play blackjack.

**Actual behavior**
I enabled it in the config, and it wouldn't do it at all. I used the most recent version.

**Comment by OsOmE1** [comment]
Include your config please

**Comment by dankgrinder** [comment]
Please include: relevant configuration, logs and environment

**Comment by TheCrazyInsanity** [comment]
set the minimum to something lower.

**Comment by Ixyk-Wolf** [comment]
I literally have no way to get my config, it is on a remote server. Everything is at the default except for some selling and search options.

**Comment by ihavezerohealth** [comment]
why can't you get it from the remote server?

**Comment by dankgrinder** [comment]
Feel free to reopen when you have the relevant configuration, logs and environment details ready.
