### ISSUE TITLE
Auto sell dosent work

### ISSUE THREAD

**Issue by fake10x** [dankgrinder/dankgrinder#23]
Hi developers of dankgrinder the feature auto sell dosent work the script auto sell doesn't sell items can u please fix this

User of dankgrinder

**Comment by ihavezerohealth** [comment]
Hi there.
I am not a dev nor contributor to Dank Grinder, however I am a very frequent user.
As of 10.1, auto sell is fully functioning.
Please join the support server, and I can help you there. Thank you!

**Comment by fake10x** [comment]
What's the support server

**Comment by ihavezerohealth** [comment]
Oh lordy

nvm:
https://discord.gg/JmfRZcj8

**Comment by fake10x** [comment]
Joined

**Comment by fake10x** [comment]
I'm underskyhalo btw
