### ISSUE TITLE
Avoid Suspicion 

### ISSUE THREAD

**Issue by Nevermind26** [dankgrinder/dankgrinder#26]
Hi how are you,
Hope you are doing well, so i installed this today and i realized when the bot does blackjack it says pls blackjack max and hit or stand. It would be better if you me it to pls bj max and h or s. Cause almost everyone does short form i haven't seen anyone do in the full form. So full form could make people sus. Just a suggestion hope u take it into consideration

**Comment by ihavezerohealth** [comment]
Replace all the hit with h in the config blackjack logic table

**Comment by dankgrinder** [comment]
Will be default in the next release, thanks.
