### ISSUE TITLE
Lottery

### ISSUE THREAD

**Issue by Nevermind26** [dankgrinder/dankgrinder#27]
Hi I wanted to thank you for the immediate reply to my previous suggestion,
So as you know the lottery is not auto now so we have to do it manually every hour so I was thinking whether it was possible to add it to the grinder. I did some messing around in the config but I don't think it works. Lemme copy paste what i did. I suck at programming btw.

features:
  commands:
    lottery: true
    
   
compatibility:
  lottery:
    - "yes"   
    
    
 cooldown:
    lottery: 3600
  
   
I think you guys have to enter it into the source code or something I am really not sure since I suck at programming but hope it help and you guys have awesome reply time congrats on that

**Comment by barrulik** [comment]
If it wasnt on go i would lovely make that

**Comment by dankgrinder** [comment]
As you said, you can't simply make up your own configuration like this. It has to be implemented in the source code for it to work. In a future release, custom commands will probably be made more advanced so that you can achieve something like this.
