### ISSUE TITLE
Clusters

### ISSUE THREAD

**Issue by daaankm** [dankgrinder/dankgrinder#30]
Saw the update but was confused about the clusters. What do I put into that section and what does it do?

**Comment by cluckingcluck** [comment]
I would join the discord server, https://discord.gg/FH77UpaD.

You can ask many questions there, but I would first read the README.md, https://github.com/dankgrinder

**Comment by KavyaKinjalk** [comment]
Cluster delocalizes your instances. For your master instance to work properly, you need all the instances to be in the same server. By creating multiple clusters you can make multiple master instances for multiple servers.

**Comment by daaankm** [comment]
Sorry I’m new to this but what does delocalizing your instances do?

**Comment by KavyaKinjalk** [comment]
Ill be practical here. if you add 50 accounts in one server, and if one account gets caught, then all 50 of your accounts will get banned, and you can be sure of it. But if you make more servers with less instances, for example 20, then only 20 accounts will get banned instead of 50

**Comment by daaankm** [comment]
Ohh makes sense, how do you get a cluster though? Like, what should I put in the section.

**Comment by KavyaKinjalk** [comment]
`clusters:
  default:
    master:
      // stuff here
    instances:
      // more stuff
  your_cool_cluster_name:
    master:
      // stuff here
    instances:
      // more stuff`

**Comment by KavyaKinjalk** [comment]
```go
clusters:
  default:
    master:
      // stuff here
    instances:
      // more stuff
  your_cool_cluster_name:
    master:
      // stuff here
    instances:
      // more stuff
```

**Comment by daaankm** [comment]
So what do I type for // stuff here

**Comment by KavyaKinjalk** [comment]
go read the readme

**Comment by daaankm** [comment]
It tells me what it does but not what to put unless I’m missing something

**Comment by KavyaKinjalk** [comment]
bruh, just put what is written there in the config file, I just told you ho to add another cluster
