### ISSUE TITLE
Custom Bj Amount 

### ISSUE THREAD

**Issue by Zorral** [dankgrinder/dankgrinder#32]
After using this for a while, (it has been working great btw other than this reason im about to mention!) I realized that it was losing a lot of money and not being able to bj again, so I was wondering if there is a way for me to set the bj amount to something else instead of max (perhaps a certain percentage of my current wallet or a set figure). Thanks!

**Comment by dankgrinder** [comment]
This has always been a feature. See https://github.com/dankgrinder/dankgrinder#auto-blackjack-object
