### ISSUE TITLE
Pause Below Amount

### ISSUE THREAD

**Issue by ihavezerohealth** [dankgrinder/dankgrinder#34]
**Description**  
I would like to _ATTEMPT_ to make a pause_below_balance feature. 

**Affected components**  
config/config.go: Reading the yaml
config/validate.go: Added an error if pause_below_balance is below 0
instance/commands.go: Added a thing that _could_ (well, should) compare the balance to the PauseBelowBalance thingy
config.yml: Added another thing under the auto-gift section

**Additional comments**  
Very unlikely I actually do it and get it working, but opening a request just to make sure I don't waste my "precious" hours on something that is already being worked on.

**Comment by dankgrinder** [comment]
Go ahead!

**Comment by KavyaKinjalk** [comment]
I will suggest you to fork the repo and then after making the changes, make a pull request

**Comment by cfschilham** [comment]
Are you still working on this and planning to PR?

**Comment by dankgrinder** [comment]
Is this still something you are working on and planning to make a PR on?

**Comment by ihavezerohealth** [comment]
nah, close it please
