### ISSUE TITLE
AutoWork

### ISSUE THREAD

**Issue by BushsPintoBeans** [dankgrinder/dankgrinder#37]
Ngl it would be pretty cool if u could add a function to the bot so it would auto work for you. also maybe auto pls daily if u afk for a LOOOONG time

**Comment by V4NSH4J** [comment]
Heya! For auto pls daily, you could make a custom command
Set the value as "pls daily" and interval as 86400 

I don't think Grind95 is doing a pls work.

**Comment by dankgrinder** [comment]
Duplicate of #7

**Comment by BushsPintoBeans** [comment]
> Heya! For auto pls daily, you could make a custom command
> Set the value as "pls daily" and interval as 86400
> 
> I don't think Grind95 is doing a pls work.

how would I put that in? where would I put it in the config folder?
