### ISSUE TITLE
Easier config 

### ISSUE THREAD

**Issue by PiggyAwesome** [dankgrinder/dankgrinder#39]
it would be amazing if you could have a .txt file with tokens and a .txt file with channel ids
The grinder would then a random token and a random channel id and use it as an instance

It takes hours to input the channel ids and tokens into the quotation marks ant this  will speed up the progess.

**Comment by PiggyAwesome** [comment]
ps stop staling my profile

**Comment by OsOmE1** [comment]
Attention seeking much?

**Comment by ihavezerohealth** [comment]
Get out.

**Comment by PiggyAwesome** [comment]
no

**Comment by PiggyAwesome** [comment]
i have an actual suggestion

**Comment by PiggyAwesome** [comment]
lol its github good luck with that

**Comment by dankgrinder** [comment]
Ignoring the irrelevant and spammy comment that I deleted, this is not something that is likely to happen. Just use an IDE with multiple carets.
