### ISSUE TITLE
Custom responses

### ISSUE THREAD

**Issue by bainchild** [dankgrinder/dankgrinder#41]
a way to add custom responses to respond to events like if the bot asks you if you want to give a person a item
![Are you sure](https://user-images.githubusercontent.com/55368789/117358922-91748b80-ae6b-11eb-8004-1a38f73c5052.PNG)

**Comment by jsmoment** [comment]
add
pls settings confirmations false
to custom commands and let every account run it, then remove it

**Comment by bainchild** [comment]
Thanks
