### ISSUE TITLE
Auto Snakeeyes

### ISSUE THREAD

**Issue by BushsPintoBeans** [dankgrinder/dankgrinder#42]
Auto snake eyes would be cool (=

**Comment by V4NSH4J** [comment]
Hey! Statistically, running auto snake eyes will not be profitable. Anyways, you may add "pls se <amount>" under custom commands and set it's interval accordingly. View the readme file for more on how to do this!

**Comment by dankgrinder** [comment]
Yep, you can implement this yourself using custom commands as explained by @V4NSH4J.
