### ISSUE TITLE
Dank Memer Update

### ISSUE THREAD

**Issue by dankboi3290** [dankgrinder/dankgrinder#43]
the new update introduced a lot of things, when can we see any updates to the grinder?

**Comment by dankboi3290** [comment]
sorry i absolutely love the grinder youve made and it works amazingly so was wondering about update

**Comment by 1337-69420** [comment]
Also prime-time to add confirmation support to auto_gift and other cmds :) (just a suggestion)

**Comment by dankboi3290** [comment]
> Also prime-time to add confirmation support to auto_gift and other cmds :) (just a suggestion)
but confimations can just be turned off its waste of effort for him

**Comment by dankgrinder** [comment]
I do not have the time to update Dank Grinder at the moment, there might be an update in the future, when I have the time
