### ISSUE TITLE
Could you explain how you are able to remotely open up discord? 

### ISSUE THREAD

**Issue by Zorral** [dankgrinder/dankgrinder#44]
The code is amazing by the way but I was wondering how you managed to log into discord remotely, if anyone knows please let me know! Thanks in advance!

**Comment by jsmoment** [comment]
what do you mean by log into discord remotely

**Comment by Zorral** [comment]
Like how are you able to log into discord?

**Comment by Zorral** [comment]
It's clearly not done on a browser in the user's computer so where and how is it done? (by if I ask some stupid questions that because im not very knowledgeable about coding sorry)

**Comment by 1337-69420** [comment]
It's done using the discord API if you didn't know. The bot makes requests to discord servers to send the messages directly rather than using a client.

**Comment by ihavezerohealth** [comment]
The dankgrinder creator was being really long-winded and decided to write his own bloody Discord API Wrapper. You can see it in the discord folder.
If you'd like me to explain better, message ihavezerohealth#5451 on Discord.
I don't know GoLang very well, but I would be able to show you _very roughly_ what does what.

**Comment by Zorral** [comment]
thanks you all!

**Comment by Zorral** [comment]
I sent you are friend request, could you accept it?

**Comment by 1337-69420** [comment]
also please close the issue now

**Comment by Zorral** [comment]
wait which api?

**Comment by Zorral** [comment]
alright sorry

**Comment by 1337-69420** [comment]
you can also add axolot#9382 for a bit of explanation

**Comment by pani7777** [comment]
uhh discord api

**Comment by dankgrinder** [comment]
The same way your browser is able to interact with Discord. Both the user interface you use in your browser or desktop application and Dank Grinder interact with the same back-end. It's just that Dank Grinder has no fancy user interface and interacts with it in a much simpler way than the official Discord client would.

You can send messages by making a POST request to the Discord API and receive incoming messages by establishing a websocket connection with Discord and listening for events such as `MESSAGE_CREATE`. This is all extensively documented [here](https://discord.com/developers/docs/intro).

Hope that answers your question.
