### ISSUE TITLE
A neat suggestion for farming coins.

### ISSUE THREAD

**Issue by AtpZombie42** [dankgrinder/dankgrinder#46]
Hello, my name is ATP Zombie and a fairly new user of dank grinder. I wanted to talk about the command "pls trivia" in this suggestion. What the command does is it shows you a trivial question, and if you get it right you may get from 500-2000 coins.
I'm not sure how auto solving it would work but I'm sure you can figure it out, one bot (dank helper) has already managed that.

**Comment by someone-ex** [comment]
I was thinking of "pls work" for the jobs too but that would require a lot of time to get the jobs ig but it'll be worth it with the new update.

**Comment by AtpZombie42** [comment]
V4NSH4J has added this, I'll close this.
