### ISSUE TITLE
Master

### ISSUE THREAD

**Issue by Physcopat** [dankgrinder/dankgrinder#47]
What should i add to the master instance so it autoshares itmes

**Comment by OsOmE1** [comment]
https://github.com/dankgrinder/dankgrinder#auto-gift-object

**Comment by Physcopat** [comment]
> https://github.com/dankgrinder/dankgrinder#auto-gift-object

but if i just enable it it wont know to send to whom

**Comment by OsOmE1** [comment]
"to the master instance" is what you said. This feature does exactly that if you'd have read it. It says it in the documentation but i'll quote it here "Whether or not to enable automatic gifting to the master instance".

**Comment by Physcopat** [comment]
i dont get it like i have to enbale the auto gift but when i do so it does not send to anyone so do i have put something that it sends to someone.

**Comment by OsOmE1** [comment]
It gifts items to the master instance please read the documentation carefully

**Comment by Physcopat** [comment]
i am not understanding anything :c

**Comment by OsOmE1** [comment]
Everything you need is in the documentation for further support you can join the discord server

**Comment by ZynxXCandy** [comment]
> i am not understanding anything :c

I think you have to put the person you want to send stuff to in the master thing.

**Comment by Physcopat** [comment]
> > i am not understanding anything :c
> 
> I think you have to put the person you want to send stuff to in the master thing.

i tried that but then the .exe wont open

**Comment by ZynxXCandy** [comment]
> > > i am not understanding anything :c
> > 
> > 
> > I think you have to put the person you want to send stuff to in the master thing.
> 
> i tried that but then the .exe wont open

What did you use? The discord ID? Or a token?

**Comment by Physcopat** [comment]
oh wait nvm i understood

**Comment by RealHeha** [comment]
> > > > i am not understanding anything :c
> > > 
> > > 
> > > I think you have to put the person you want to send stuff to in the master thing.
> > 
> > 
> > i tried that but then the .exe wont open
> 
> What did you use? The discord ID? Or a token?

I used the token, ID, and the name and tag, the exe just instantly closes.
