### ISSUE TITLE
Making 3 instances run for 6 hours and then being dormant for 18

### ISSUE THREAD

**Issue by AtpZombie42** [dankgrinder/dankgrinder#49]
How would I make the bot run 3 instances? it errors on line 16 (channel id)

**Comment by dankgrinder** [comment]
Your yaml syntax is probably invalid. Please attach your config with any tokens removed.

**Comment by AtpZombie42** [comment]
clusters:
  default:
    master:
      token: "pro"
      channel_id: "getty"
     instances:
      token: "noob 1"
      channel_id: "talky"
      token: "noob 2"
      channel_id: "talky"

**Comment by someone-ex** [comment]
clusters:
  default:
    master:
      token: "pro"
      channel_id: "getty"
    instances:
        - token: "noob 1"
          channel_id: "talky"
        - token: "noob 2"
          channel_id: "talky"
          
          
          try it with the '- token' it should work well

**Comment by AtpZombie42** [comment]
Alright, thanks for the help
