### ISSUE TITLE
Add dig command and add a script that fills rare events

### ISSUE THREAD

**Issue by sandwitcheater42** [dankgrinder/dankgrinder#50]
For example, if you do pls fish for a while, you encounter a boss and you have to type a certain word/sentence, a script fills the sentence for you like in events

**Comment by dankgrinder** [comment]
The only scripts in Dank Grinder are scripts for building and compressing the executable and config file. 

And yes, if I have the time to update Dank Grinder I will implement this.

**Comment by ihavezerohealth** [comment]
lmfao but everything is a script
