### ISSUE TITLE
Need help 

### ISSUE THREAD

**Issue by empty8005** [dankgrinder/dankgrinder#51]
So you can use this tool on windows mac and Linux but anyone know how can I use it on android or I need a pc for this kind regard 🙇 my discord id is my name 😀 (empty#8005)

**Comment by ihavezerohealth** [comment]
Please read the README.md file before asking questions.

**Comment by empty8005** [comment]
Bruh i dont understand how can i use it on android phone just say no or yes

**Comment by ihavezerohealth** [comment]
Right, read the fucking readme. That'll tell you your no and yes

**Comment by dankgrinder** [comment]
Android is not supported, however, I've heard of people using a Linux emulator to run it.

**Comment by 1337-69420** [comment]
Use termux

**Comment by empty8005** [comment]
Ok also where from i get termux ?;(

**Comment by jsmoment** [comment]
> Ok also where from i get termux ?;(

https://play.google.com/store/apps/details?id=com.termux
