### ISSUE TITLE
Oof last question 

### ISSUE THREAD

**Issue by empty8005** [dankgrinder/dankgrinder#56]
I have clone tool in termux also edited it but I am unable to find which pkg I have to install so I can run config.yml also how to get token in android I serach on yt but i found nothing 😥🤧

**Comment by ihavezerohealth** [comment]
bro you be crying over this shit?
then go cry lmao

**Comment by empty8005** [comment]
> bro you be crying over this shit?
> then go cry lmao

Help pls

**Comment by dankgrinder** [comment]
This is another duplicate of #51 and not relevant to Dank Grinder. Title is still very bad, contrary to my request. Stop making issues about this, I'm fed up
