### ISSUE TITLE
Is this  safe (dankgrinder for android)

### ISSUE THREAD

**Issue by empty8005** [dankgrinder/dankgrinder#59]
I asked for android support and a discord guy ask my username and said that he will help me out he was nice tho,
 he said you need arm64 not amd 64 compile and he gave me his dankgrinder compiler [Here ]
(https://cdn.discordapp.com/attachments/846610339319906324/846750075761197057/dankgrinder-arm64)
 but I am worried about getting rated also I don't know about cods if any of you know cods then tell me is this safe or not @OsOmE1

**Comment by ihavezerohealth** [comment]
Who messaged you? Give me their name and tag, please.
For now, DO NOT RUN IT.

its prolly piggy

**Comment by empty8005** [comment]
> Who messaged you? Give me their name and tag, please.
> For now, DO NOT RUN IT.
> 
> its prolly piggy

js#0814 his tag also i didn't run that program i know about possible damage

**Comment by OsOmE1** [comment]
As far as I can see there is nothing wrong with this binary. I'd still throw it through a virus scanner just to be sure, but it looks to be a legitimate copy of dankgrinder.

**Comment by empty8005** [comment]
> As far as I can see there is nothing wrong with this binary. I'd still throw it through a virus scanner just to be sure, but it looks to be a legitimate copy of dankgrinder.

Thanks will this work for android cau he said so

**Comment by 1337-69420** [comment]
> > As far as I can see there is nothing wrong with this binary. I'd still throw it through a virus scanner just to be sure, but it looks to be a legitimate copy of dankgrinder.
> 
> Thanks will this work for android cau he said so

only if your device is arm64, android devices can also be arm(32)

**Comment by dankgrinder** [comment]
We do not support Android. I've told you this like twice now, yet still, here you are making more issues about it. I will revoke your right to make new issues.
