### ISSUE TITLE
Add pls work as an option!

### ISSUE THREAD

**Issue by Official-Darkn** [dankgrinder/dankgrinder#7]
### While yes, there are a ton of different jobs in Dank Memer as found in pls work list,
You can make it where the user has to get a certain job like work as a Cosplayer then the bot will autofarm any pls work tasks the user has to do.

**Comment by dankgrinder** [comment]
Wouldn't the additional income on an hourly basis be negligible?

**Comment by Official-Darkn** [comment]
> Wouldn't the additional income on an hourly basis be negligible?

What do you mean?

**Comment by dankgrinder** [comment]
If you can work every half hour, and you earn a few thousand coins every time you work, you would only earn a few thousand extra coins every hour

**Comment by Official-Darkn** [comment]
> > > Wouldn't the additional income on an hourly basis be negligible?
> > 
> > 
> > What do you mean?
> 
> If you can work every half hour, and you earn a few thousand coins every time you work, you would only earn a few thousand extra coins every hour

Sure you would only earn a few thousand extra coins every hour, but it's still more coins. Not only that but you get promoted more easily, allowing you to get even more coins. With this you can get more than just a thousand and get up to like the tens of thousands of coins, I know this since I use pls work a lot.

**Comment by dankgrinder** [comment]
I will look into the profitability and if it's significant it might make it into a later release

**Comment by 1337-69420** [comment]
> I will look into the profitability and if it's significant it might make it into a later release

There are work specific items now, I'd say priority must be reconsidered
