### ISSUE TITLE
No token

### ISSUE THREAD

**Issue by Ethorologiumricinum** [dankgrinder/dankgrinder#72]
I have wrote my token but it is still giving a no token error i tried multiple times tried new accs but i am still getting the no token error help anyone?

**Comment by V4NSH4J** [comment]
Hey! Here's a few things you may wanna try!
1) make sure you're token is right. 
2) make sure your indentations (amount of spacing) in the config for the token part is right 
3) make sure you're not using an older config with a newer version of DankGrinder (clusters update caused this)

If you still face any issues, join the discord with an *alt account* which is in no way linked with your main. I'll help you out!

**Comment by Ethorologiumricinum** [comment]
> Hey! Here's a few things you may wanna try!
> 
> 1. make sure you're token is right.
> 2. make sure your indentations (amount of spacing) in the config for the token part is right
> 3. make sure you're not using an older config with a newer version of DankGrinder (clusters update caused this)
> 
> If you still face any issues, join the discord with an _alt account_ which is in no way linked with your main. I'll help you out!

1.It is right
2.spacing is right 
3.i just downloaded it so it cant be old

**Comment by V4NSH4J** [comment]
> > Hey! Here's a few things you may wanna try!
> > 
> > 1. make sure you're token is right.
> > 2. make sure your indentations (amount of spacing) in the config for the token part is right
> > 3. make sure you're not using an older config with a newer version of DankGrinder (clusters update caused this)
> > 
> > If you still face any issues, join the discord with an _alt account_ which is in no way linked with your main. I'll help you out!
> 
> 1.It is right
> 2.spacing is right 
> 3.i just downloaded it so it cant be old 

Join the discord on an alt. Bot mods are there every account gets banned so bring a disposable one
