### ISSUE TITLE
New gui buttons can the bot click them?

### ISSUE THREAD

**Issue by DiscrimIsPog** [dankgrinder/dankgrinder#86]
I was wondering about the new gui buttons and if the bot will click them 
![image](https://user-images.githubusercontent.com/61711429/133182851-bc179483-2911-4034-ab0b-d94f2049b040.png)

**Comment by ghost** [comment]
https://github.com/V4NSH4J/dankgrinder
this version work with buttons

**Comment by JoonyWoony** [comment]
yes it does ofc

**Comment by DiscrimIsPog** [comment]
ty @Catawbas
