### ISSUE TITLE
Add a gambler

### ISSUE THREAD

**Issue by SalazariQ** [dankgrinder/dankgrinder#9]
So what I would like is if you can add a mode where it does "pls bet max" forever, and when your balance is 10M+ (when you can't gamble anymore) it automatically deposits a custom amount which can be edited, and also make it use the fidget spinner automatically for the extra multiplier when gambling. this could earn me 100s of millions easily. Also if possible make it withdraw 5M whenever the bank balance is 0.

**Comment by Zyzy69** [comment]
YES THIS WOULD BE PERFECT

**Comment by Official-Darkn** [comment]
> So what I would like is if you can add a mode where it does "pls bet max" forever, and when your balance is 10M+ (when you can't gamble anymore) it automatically deposits a custom amount which can be edited, and also make it use the fidget spinner automatically for the extra multiplier when gambling. this could earn me 100s of millions easily. Also if possible make it withdraw 5M whenever the bank balance is 0.

This would be awesome to do, but at the same time it's always chance chance. You will always lose money and gain some. So it's just chance chance.

**Comment by dankgrinder** [comment]
Similar features are being worked on
