### ISSUE TITLE
Doesnt react

### ISSUE THREAD

**Issue by Faizan2k7** [dankgrinder/dankgrinder#91]
**Expected behavior**
like isnt it supposed to click yes or no when sharing to main and when using tide etc?

**Actual behavior**
it doesnt react

**Steps to reproduce**
How the problem can be reproduced from a clean installation

**Logs**
If relevant, paste any errors or other logs here.

**Environment**
OS: windows
Dank Grinder version: buttons 2.0
Config: make sure to remove your tokens! 

shifts:
  - state: "active"
    duration:
      base: 7200
      variation: 1800
  - state: "dormant"
    duration:
      base: 1800
      variation: 1800
  - state: "active"
    duration:
      base: 7200
      variation: 3600
  - state: "dormant"
    duration:
      base: 32400
      variation: 3600

features:
  commands:
    beg: true
    postmeme: true
    search: true
    highlow: true
    fish: true
    hunt: true
    dig: true
    work: true
    trivia: true
    crime : true
    guess: false

  scratch:
    enable: true
    amount: 0
    priority: false

  custom_commands:
  - value: "pls use lucky"
    interval: 900
  - value: "pls dep all"
    interval: 5
  auto_buy:
    fishing_pole: true
    hunting_rifle: true
    laptop: true
    shovel: true
  auto_sell:
    enable: false
    items:
      - "boar"
      - "dragon"
      - "duck"
      - "fish"
      - "deer"
      - "rabbit"
      - "skunk"
  auto_gift:
    enable: true
    items:
      - "bank"
      - "pizza"
      - "boar"
      - "dragon"
      - "duck"
      - "fish"
      - "deer"
      - "rabbit"
      - "skunk"
      - "kraken"
      - "lucky"

  auto_share:
    enable: true
    maximum_balance: 8000000
    minimum_balance: 5000000
  auto_blackjack:
    enable: true
    amount: 0
    pause_below_balance: 100000
    pause_above_balance: 5000000
    logic_table:
      2:
        4: "h"
        5: "h"
        6: "h"
        7: "h"
        8: "h"
        9: "h"
        10: "h"
        11: "h"
        12: "h"
        13: "h"
        14: "h"
        15: "s"
        16: "s"
        17: "s"
        18: "s"
        19: "s"
        20: "s"
        soft12: "h"
        soft13: "h"
        soft14: "h"
        soft15: "h"
        soft16: "h"
        soft17: "s"
        soft18: "s"
        soft19: "s"
        soft20: "s"
      3:
        4: "h"
        5: "h"
        6: "h"
        7: "h"
        8: "h"
        9: "h"
        10: "h"
        11: "h"
        12: "h"
        13: "h"
        14: "h"
        15: "s"
        16: "s"
        17: "s"
        18: "s"
        19: "s"
        20: "s"
        soft12: "h"
        soft13: "h"
        soft14: "h"
        soft15: "h"
        soft16: "h"
        soft17: "s"
        soft18: "s"
        soft19: "s"
        soft20: "s"
      4:
        4: "h"
        5: "h"
        6: "h"
        7: "h"
        8: "h"
        9: "h"
        10: "h"
        11: "h"
        12: "h"
        13: "h"
        14: "s"
        15: "s"
        16: "s"
        17: "s"
        18: "s"
        19: "s"
        20: "s"
        soft12: "h"
        soft13: "h"
        soft14: "h"
        soft15: "h"
        soft16: "h"
        soft17: "s"
        soft18: "s"
        soft19: "s"
        soft20: "s"
      5:
        4: "h"
        5: "h"
        6: "h"
        7: "h"
        8: "h"
        9: "h"
        10: "h"
        11: "h"
        12: "h"
        13: "h"
        14: "s"
        15: "s"
        16: "s"
        17: "s"
        18: "s"
        19: "s"
        20: "s"
        soft12: "h"
        soft13: "h"
        soft14: "h"
        soft15: "h"
        soft16: "h"
        soft17: "s"
        soft18: "s"
        soft19: "s"
        soft20: "s"
      6:
        4: "h"
        5: "h"
        6: "h"
        7: "h"
        8: "h"
        9: "h"
        10: "h"
        11: "h"
        12: "h"
        13: "h"
        14: "s"
        15: "s"
        16: "s"
        17: "s"
        18: "s"
        19: "s"
        20: "s"
        soft12: "h"
        soft13: "h"
        soft14: "h"
        soft15: "h"
        soft16: "h"
        soft17: "s"
        soft18: "s"
        soft19: "s"
        soft20: "s"
      7:
        4: "h"
        5: "h"
        6: "h"
        7: "h"
        8: "h"
        9: "h"
        10: "h"
        11: "h"
        12: "h"
        13: "h"
        14: "h"
        15: "h"
        16: "h"
        17: "s"
        18: "s"
        19: "s"
        20: "s"
        soft12: "h"
        soft13: "h"
        soft14: "h"
        soft15: "h"
        soft16: "h"
        soft17: "s"
        soft18: "s"
        soft19: "s"
        soft20: "s"
      8:
        4: "h"
        5: "h"
        6: "h"
        7: "h"
        8: "h"
        9: "h"
        10: "h"
        11: "h"
        12: "h"
        13: "h"
        14: "h"
        15: "h"
        16: "h"
        17: "s"
        18: "s"
        19: "s"
        20: "s"
        soft12: "h"
        soft13: "h"
        soft14: "h"
        soft15: "h"
        soft16: "h"
        soft17: "h"
        soft18: "s"
        soft19: "s"
        soft20: "s"
      9:
        4: "h"
        5: "h"
        6: "h"
        7: "h"
        8: "h"
        9: "h"
        10: "h"
        11: "h"
        12: "h"
        13: "h"
        14: "h"
        15: "h"
        16: "h"
        17: "s"
        18: "s"
        19: "s"
        20: "s"
        soft12: "h"
        soft13: "h"
        soft14: "h"
        soft15: "h"
        soft16: "h"
        soft17: "h"
        soft18: "s"
        soft19: "s"
        soft20: "s"
      10:
        4: "h"
        5: "h"
        6: "h"
        7: "h"
        8: "h"
        9: "h"
        10: "h"
        11: "h"
        12: "h"
        13: "h"
        14: "h"
        15: "h"
        16: "h"
        17: "s"
        18: "s"
        19: "s"
        20: "s"
        soft12: "h"
        soft13: "h"
        soft14: "h"
        soft15: "h"
        soft16: "h"
        soft17: "h"
        soft18: "s"
        soft19: "s"
        soft20: "s"
      A:
        4: "h"
        5: "h"
        6: "h"
        7: "h"
        8: "h"
        9: "h"
        10: "h"
        11: "h"
        12: "h"
        13: "h"
        14: "h"
        15: "h"
        16: "h"
        17: "h"
        18: "s"
        19: "s"
        20: "s"
        soft12: "h"
        soft13: "h"
        soft14: "h"
        soft15: "h"
        soft16: "h"
        soft17: "h"
        soft18: "s"
        soft19: "s"
        soft20: "s"
  auto_tidepod:
    enable: true
    buy_lifesaver_on_death: true
  balance_check:
    enable: true
    interval: 180
  log_to_file: false
  verbose_log_to_stdout: false
  debug: false

compatibility:
  allowed_searches:
    - "area51"
    - "bank"
    - "grass"
    - "purse"
    - "mel's room"

  allowed_crimes:
    - "tax evasion"
  allowed_scrambles:
    - "scoop"
    - "dirty"
    - "ground"
    - "burrow"
    - "spider"
    - "shovel"
    - "trowel"
    - "unearth"
    - "uncover"
    - "ladybug"
    - "excavate"
    - "stickbug"
  dig_cancel:
    - "LOL idk this"
    - "No hable english"
  allowed_ftb:
    - "I am a dwarf and I diggy the hole"
    - "Digging is my passion"
    - "I hope I find some treasure"
    - "I have never dug up a body"
    - "I will dig all day and all night"
    - "Never have I ever dug up a body"
  allowed_scrambles_work:
    # discord mod
    - "carl-bot"
    - "moderator"
    - "permissions"
    - "audit"
    - "slowmode"
    - "discord"
    - "admin"
    - "hammer"
    - "welcome"
    - "softban"
    - "links"
    - "advertising"
    - "support"
    - "voice"
    - "rules"
    # fast food cook
    - "chicken"
    - "sausage"
    - "onion"
    - "salad"
    - "mustard"
    - "sauce"
    - "hamburger"
    - "cheeseburger"
    - "taco"
    - "wendys"
    - "food"
    - "fries"
    - "patty"
    - "tomato"
    - "sirloin"
    - "cheap"
    - "lettuce"
    - "ketchup"
    # babysitter
    - "baths"
    - "babysitter"
    - "bedtime"
    - "child"
    - "children"
    - "childcare"
    - "cleaning"
    - "cooking"
    - "daycare"
    - "diaper"
    - "helpful"
    - "house"
    - "meals"
    - "nanny"
    - "safety"
    # housewife
    - "abode"
    - "chores"
    - "cleaning"
    - "coffee"
    - "companion"
    - "cooking"
    - "dishes"
    - "dwelling"
    - "homemaker"
    - "household"
    - "mommy"
    - "partner"
    - "spouse"
    # streamer
    - "shroud"
    - "copyright"
    - "donation"
    - "drlupo"
    - "gaming"
    - "kappa"
    - "kreygasm"
    - "league"
    - "melmsie"
    - "minecraft"
    - "pogchamp"
    - "poggers"
    - "prime"
    - "residentsleeper"
    - "stream"
    - "timthetatman"
    - "wutface"
    - "4head"
    # youtuber
    - "annotations"
    - "avatar"
    - "channel"
    - "clickbait"
    - "cocomelon"
    - "community"
    - "copyright"
    - "demographics"
    - "description"
    - "dislike"
    - "drama"
    - "featured"
    - "google"
    - "matpat"
    - "money"
    - "mrbeast"
    - "pewdiepie"
    - "smosh"
    - "sponsored"
    - "subscribe"
    - "subtitles"
    - "thumbnails"
    - "tseries"
    - "video"
    - "views"
    - "watermark"
    - "wojcicki"
    # hunter
    - "animal"
    - "antelope"
    - "antlers"
    - "arrow"
    - "blind"
    - "bullet"
    - "gunshot"
    - "hunting"
    - "knife"
    - "rifle"
    - "scope"
    - "sentry"
    - "tracks"
    - "trail"
    - "woods"
    # fisher
    - "bobber"
    - "boots"
    - "fisherman"
    - "fishing"
    - "float"
    - "ocean"
    - "sinker"
    - "shark"
    - "spinner"
    - "tackle"
    - "trolling"
    - "water"
    - "whale"
    # bartender
    - "alcohol"
    - "beverage"
    - "blend"
    - "chaser"
    - "chill"
    - "cocktail"
    - "drink"
    - "garnish"
    - "house"
    - "mixer"
    - "rocks"
    - "serve"
    - "shooter"
    - "spill"
    - "strain"
    - "twist"
    - "virgin"
    - "whiskey"
    # robber
    - "bandit"
    - "fence"
    - "grift"
    - "heist"
    - "lockpick"
    - "money"
    - "prison"
    - "robber"
    - "robbery"
    - "armed"
    - "steal"
    - "undercover"
    - "valuables"
    # police
    - "arrested"
    - "arson"
    - "baton"
    - "crime"
    - "criminal"
    - "handcuffs"
    - "murder"
    - "officer"
    - "police"
    - "thief"
    # teacher
    - "chemical"
    - "bell"
    - "class"
    - "classroom"
    - "down"
    - "give"
    - "going"
    - "held"
    - "office"
    - "school"
    - "settle"
    - "this"
    - "true"
    - "will"
    - "year"
    - "your"
    # musician
    - "album"
    - "conform"
    - "cowbell"
    - "drums"
    - "getting"
    - "groove"
    - "guitar"
    - "songs"
    - "sounds"
    - "spotify"
    - "stinger"
    - "stop"
    - "piano"
    # shopkeeper
    - "advertisement"
    - "alcohol"
    - "apple"
    - "coupon"
    - "coupon"
    - "huntingrifle"
    - "inventory"
    - "lifesaver"
    - "pepetrophy"
    - "profit"
    - "shopkeeper"
    - "stonks"
    # gamer
    - "carry"
    - "cheese"
    - "feeding"
    - "gamer"
    - "gaming"
    - "jungle"
    - "laning"
    - "stack"
    - "ultimate"
    # manager
    - "administrator"
    - "costs"
    - "costs"
    - "director"
    - "innovation"
    - "leader"
    - "manager"
    - "metrics"
    - "money"
    - "office"
    - "planning"
    - "process"
    - "project"
    - "quality"
    - "resources"
    - "revenue"
    # developer
    - "array"
    - "coding"
    - "developer"
    - "development"
    - "hacker"
    - "javascript"
    - "kotlin"
    - "object"
    - "program"
    - "programming"
    - "scala"
    - "swift"
    # day trader
    - "bears"
    - "bulls"
    - "enlading"
    - "float"
    - "freeding"
    - "gambling"
    - "index"
    - "investment"
    - "market"
    - "money"
    - "profit"
    - "regulation"
    - "return"
    - "shares"
    - "split"
    - "stocks"
    - "stonks"
    - "wallstreet"
    # santa claus
    - "beard"
    - "bells"
    - "belly"
    - "chimney"
    - "christmas"
    - "claus"
    - "cookies"
    - "elves"
    - "gifts"
    - "presents"
    - "reindeer"
    - "rooftop"
    - "rudolph"
    - "saint"
    - "santa"
    - "sleigh"
    - "snowball"
    - "snowman"
    # politician
    - "country"
    - "executive"
    - "leader"
    - "legislature"
    - "office"
    - "taxes"
    # vet
    - "animals"
    - "blood"
    - "checkup"
    - "collar"
    - "fleas"
    - "medicine"
    - "microchip"
    - "muzzle"
    - "needle"
    - "neuter"
    - "veterinary"
    # pharmacist
    - "therapeutic"
    - "generic"
    - "toxicology"
    - "prescription"
    - "dispensing"
    # lawyer
    - "admissible"
    - "affidavit"
    - "affirmed"
    - "counsel"
    - "defendant"
    - "defense"
    - "deposition"
    - "discovery"
    - "judge"
    - "officer"
    - "plaintiff"
    - "precedent"
    - "proof"
    # doctor
    - "antibiotic"
    - "bandaid"
    - "broken"
    - "checkup"
    - "doctor"
    - "gauze"
    - "hospital"
    - "illness"
    - "medical"
    - "nurse"
    - "office"
    - "payment"
    - "research"
    - "viral"
    - "virus"
    # scientist
    - "beaker"
    - "curie"
    - "darwin"
    - "discipline"
    - "edison"
    - "education"
    - "expert"
    - "explosion"
    - "galileo"
    - "invention"
    - "liquid"
    - "newton"
    - "physicist"
    - "reaction"
    - "solid"
    - "teaching"
    # ghost
    - "apparition"
    - "banshee"
    - "bogey"
    - "creepy"
    - "demon"
    - "devil"
    - "freezing"
    - "ghost"
    - "ghoul"
    - "haunt"
    - "phantasm"
    - "phantom"
    - "poltergeist"
    - "scary"
    - "shade"
    - "skeleton"
    - "vision"
    - "wraith"
  work_cancel:
    - "I'm feeling lazy to work today"
    - "Working is for nabs"
    - "Why play dank when I gotta work here too"
    - "Why always so hard"
  allowed_hangman:
    # fast food worker
    - "How may I take your order"
    - "Would you like to super size that meal"
    - "This is a great chicken burger"
    - "That will be one dollar"
    - "We do not offer refunds"
    - "I want a refund"
    - "The shake machine is broke again"
    - "We close at midnight"
    - "The fries are in the grease"
    - "Two number 9's, a number 9 large, a number 6 with extra dip"
    - "Would you like fries with that"
    - "The delivery truck just got here"
    - "Did you want sauce with those nuggets"
    - "I do not get payed enough for this"
    - "Corporate greed does not exist because they give me free fries duh"
    - "I wonder if they will replace us with robots soon"
    - "Would you like that with a side of foot lettuce"
    # discord mod stuff
    - "Please reread the rules"
    - "The rules are pretty simple"
    - "Give that user a mute"
    - "If you dont like the rules, leave the server"
    - "Nagging is bad for your health"
    - "You don't choose the slowmode, the slowmode chooses you"
    - "This isn't the place to practice abc's"
    - "Looks like someone's on a ban streak"
    - "We're always lurking in chat"
    - "I will ban you again don't test me"
    # babysitter
    - "Can you guys just behave for once"
    - "Go to your room please"
    - "I cant stand these kids"
    - "I lost the baby again sorry"
    - "I am your nanny, not nana"
    - "I'm going to invite my boyfriend over"
    - "I do not want to change more diapers"
    - "I am not getting paid enough for this child"
    - "What do you want to eat tonight"
    # housewife
    - "Baked three dozen cookies today"
    - "Haven't left the house in two weeks"
    - "I cleaned all the dishes"
    - "I do not work for an MLM it works for me"
    - "I should get a new rug"
    - "I should join the neighborhood watch"
    - "I wonder what my spouse is doing right now"
    - "live laugh love is my motto"
    - "My kids are my full time job"
    - "Sugar daddy bought me a new vacuum"
    - "The baby puked on the floor again"
    - "The chores never end"
    - "This house is clean lets keep it that way"
    - "Working moms don't love their kids"
    - "Would you like to buy some essential oils"
    # streamer
    - "Alright who are we going to raid tonight"
    - "Can you guys make sure you donate, I need a new gaming computer"
    - "Clip it and ship it boys"
    - "Daddy Bezos please gift me some subs"
    - "Gamers rise up against Amazon"
    - "I hope I get hosted today"
    - "I will do shots for every donation I get"
    - "League is the best game to stream"
    - "Lets play some games together"
    - "Make sure you read the chat rules"
    - "Thank you for the host Dr Lupo"
    - "Thank you for the raid shroud"
    - "Thank you guys for all of the donations"
    - "Woah thanks for 1000 bits"
    # youtuber
    - "3 scary games is the best series on YouTube"
    - "90 percent of you watching are not subscribed"
    - "All hail the YouTube algorithm"
    - "And that’s just a theory, a GAME theory"
    - "Clickbait gets the good views"
    - "Guys, I need you to smash like!"
    - "It’s just a prank bro"
    - "Make sure to subscribe to the channel and hit that notification bell!"
    - "Pranks gone sexual in the hood"
    - "Subscribe to me"
    - "Top of the morning to you"
    - "Top ten videos are where the money is at"
    - "YouTube Rewind was bad"
    # hunter
    - "A bad day hunting still beats a good day working"
    - "How come I only ever get skunks"
    - "I forget where I put the bear trap"
    - "I only hunt with a bow"
    - "I heard there was a dragon near"
    - "I need a bigger gun next time"
    - "If I don't get that buck then somebody else will"
    - "No, I'm not a good shot, but I shoot often"
    - "Shucks, that’s just a cull buck"
    - "Saving people, hunting things, the family business"
    - "The placing of the bullet is everything"
    # fisher
    - "A reel expert can tackle anything"
    - "Fish tremble at the sound of my name"
    - "Good things come to those who bait"
    - "Hook line and sinker"
    - "No fishing like in the sea"
    - "Not all of us like sea shanties"
    - "The fishing is good in troubled waters"
    - "Will work for fish"
    - "Whale whale whale what do we have here"
    - "You've been schooled"
    # bartender
    - You should probably uber home"
    - "3 drinks minimum at this bar"
    - "Another drink coming right up"
    - "Let me see your ID first please"
    - "Rum and coke is my favorite drink"
    - "You are too drunk to drive tonight"
    - "You had better tip me for this"
    - "You need to be over 21 to drink"
    - "You're a little too drunk"
    - "You've had enough to drink tonight"
    - "Your credit card was declined"
    # robber
    - "I cannot wait to steal again"
    - "I have a wishlist of targets to hit"
    - "I have no problem stealing candy from babies"
    - "I hope I remembered my bolt cutters"
    - "I will rob your entire wallet in one swipe"
    - "Should I rob a person or a bank today"
    - "Time to rob another victim"
    - "Time to rob another victim"
    - "jackpot, I'm rich now"
    # police
    - "Anything you say can and will be used against you in a court of law"
    - "Dead or alive you're coming with me"
    - "I will meet you at the squad car"
    - "If you cannot afford an attorney one will be provided for you"
    - "If you post bad memes, you will be arrested"
    - "Police officers stop criminals"
    - "The captain will not be happy about this"
    - "The criminal tried  to get away"
    - "The murderer escaped the police"
    - "The neighborhood watch is stupid, I'm the law around here"
    - "The police successfully captured the bank robber"
    - "You have the right to an attorney"
    - "You have the right to remain silent"
    # teacher
    - "Children settle down"
    - "Children settle down now"
    - "Give me your phone"
    - "Go see the school nurse"
    - "I am going to have to fail you out of this class"
    - "I do not get paid enough for this"
    - "I'm going to give you detention again"
    - "No gum in my classroom"
    - "No hats while in class because we are afraid of your lice"
    - "This will be valuable your entire life"
    - "Today we will learn about chemical reactions"
    - "Today, we're going to learn about World War II"
    - "You are dismissed by me and not the bell"
    - "You need to go to the office right now"
    - "You will need to go to summer school this year"
    - "You will not use true knowledge later in life"
    - "You're getting held back again"
    # musician
    - "I am feeling the groove"
    - "I do not conform to a single genre"
    - "I need to stop getting in treble"
    - "Order my new album this weekend"
    - "You can find me on spotify"
    # shopkeeper
    - "Buy one and get one free"
    - "Did you forget your coupons"
    - "Do you want a bag for that"
    - "I sell a vast amount of goods"
    - "There is a new sale every hour"
    - "We do not offer delivery"
    - "Why are my flash sales so low these days"
    - "Will that be cash or credit"
    # gamer
    - "Anyone wanna play ranked"
    - "Get rekt noob LMAO"
    - "I cannot understand anything but videogames"
    - "I chug gfuel all day and night"
    - "I play games for a living"
    - "I'm on a massive win streak"
    - "Oh baby a triple!"
    - "That player was such a noob"
    - "who is down for a few more runs"
    # manager
    - "Can I see your resume please"
    - "Corporate wants some changes around here"
    - "I had to hand in some work to make my manager happy"
    - "I hate salary work"
    - "I make less then my hourly employees"
    - "I manage a large team of skilled workers"
    - "I will not pay you for overtime"
    - "Managers lead a team of people"
    - "Managers never go on strike"
    - "My manager is a nice person"
    - "Stop teasing the new hires"
    - "Time for your performance review"
    - "We are looking for skilled laborers"
    - "Without managers, the world would be in chaos"
    - "You will have to stay extra late tonight"
    # developer
    - "CSS is the bane of my life"
    - "I am on year 7 on my unpaid internship"
    - "I'll just push this to production, what could go wrong?"
    - "Imagine using anything other then VSCode"
    - "In about 10 years I should get my first raise"
    - "It's not my fault that it broke"
    - "JavaScript is really stupid"
    - "Mongo is totally webscale"
    - "What the hell is wrong with JavaScript"
    - "Why is everything broken in production"
    - "Why is nothing working anymore"
    - "Writing HTML is not programming"
    # day trader
    - "GME is going to the moon"
    - "Got any stock buddy?"
    - "I think today is the day I get rich"
    - "Keep an eye on those candle-sticks!"
    - "Short selling is where it's at"
    - "TSLA is not a good idea to invest in"
    - "The wolf of wall Street? More like an alley cat"
    - "Today will totally be a bear market"
    - "Yes, I am the stonks guy"
    # santa
    - "And to all a good night"
    - "I barely fit down the chimney"
    - "I have a jolly big belly"
    - "I know if you’ve been bad or good"
    - "I need to deliver these gifts"
    - "I should probably cut back on the cookies next year"
    - "I treat my elves very fairly"
    - "Leave me some cookies and milk"
    - "Mrs Claus is going to be pissed"
    - "You’re on my naughty list"
    # politician
    - "Corruption is my middle name"
    - "Eat the rich is not a political movement, it is a just cause"
    - "I am running for election in 2024"
    - "I cannot wait for politics to be boring again"
    - "Imagine inciting a riot at the capital"
    - "Show me your tax returns"
    - "THAT'S FAKE NEWS"
    - "The democrats are at it again"
    - "Time to gaslight an entire country"
    - "We are going to build the Wall around Florida"
    - "We're going to make this country shitty again"
    # vet
    - "Back again? What happened this time?"
    - "Did he really eat those smelly socks"
    - "Has it had flea medicine recently"
    - "I can save your pet sir"
    - "Make sure she keeps that cone on"
    - "Maybe trim the nails before the vet visit next time"
    - "This is going to be a ruff one"
    - "This’ll calm you down"
    - "Try harder or you will be arrested for meow-practice"
    # pharmacist
    - "Sorry we don't have any drugs to prescribe to help your IQ"
    - "You will pay for your insulin!"
    - "The DEA was just here asking questions"
    - "I happily sell drugs for a living"
    - "My drugs are the least overpriced around"
    # lawyer
    - "I believe the defendant is very guilty"
    - "I rest my case your honor"
    - "My client is innocent I swear"
    - "My hourly rate costs more than a stripper"
    - "My hourly rate is very high"
    - "Raise your right hand and repeat after me"
    - "With all due respect your honor"
    - "Your criminal record speaks for itself"
    # doctor
    - "Are you on any medication?"
    - "Do you have any concerns?"
    - "Do you understand your prescription?"
    - "I have to diagnose you again"
    - "Tell the nurse you need a snack"
    - "Statistically, 9 out of 10 injections are in vein"
    - "Take a glass of apple juice on your way out"
    - "Try hard, there is no cure for stupidity… yet"
    - "What brought you here today?"
    # scientist
    - "Bill Nye the science guy rules"
    - "Can you stop rubbing your molecules on me"
    - "Climate change requires real action to solve"
    - "Energy equals mass times the speed of light squared"
    - "For every action there is an equal and opposite reaction"
    - "Force equals mass times acceleration"
    - "Only two things are infinite the universe and human stupidity, and I'm not sure about the former"
    - "Research is what I'm doing when I don't know what I'm"
    - "Science never solves a problem without creating ten more"
    - "Scientific research is one of the most exciting and rewarding occupations"
    - "Thank god for gravity"
    - "The distance between insanity and genius is measured only by success"
    # ghost
    - "Bro I swear that cold spot isn't mine"
    - "Do you even haunt bro"
    - "Has anyone seen my rattling chains"
    - "If you've got it, haunt it!"
    - "I have never possessed someone"
    - "I hope you do not get GHOSTED LOL"
    - "I'm gonna haunt that person so hard"
    - "I swear to god it's always too cold here"
    - "Oh no, im leaking ectoplasm"
    - "Phasmaphobia is so realistic"
    - "Satan's in a mood again"
    - "Spooky scary skeleton"
  fish_cancel:
    - "my fishing IQ is too low"
  allowed_scrambles_fish:
    - "fishy"
    - "jellyfish"
    - "squid"
    - "fishing"
    - "whale"
    - "ocean"
    - "water"
    - "trout"
  allowed_fish_ftb:
    - "woah a big one"
    - "this is very fishy"
    - "big bait catches big fish"
    - "the fish are acting super fishy"
    - "big big fishy"
    - "get the camera ready mom"
    - "the fish says glub"
    - "hook line and sinker"
  search_mode: 2
  crime_mode: 2
  cooldown:
    beg: 48
    search: 38
    highlow: 33
    postmeme: 63
    fish: 63
    hunt: 63
    blackjack: 13
    sell: 6
    gift: 26
    share: 13
    dig: 42
    work: 3600
    trivia: 15
    crime: 55
    scratch: 15
    guess: 30
  await_response_timeout: 7

suspicion_avoidance:
  typing:
    variation: 250
    speed: 450
  message_delay:
    base: 100
    variation: 400
  button_press:
    base: 15000
    variation: 1000

**Comment by ghost** [comment]
tidepod doesn't work since no one use them on there grinding alts.
and you can add 'pls settings confirmations false' in custom  command so your alts will share/gift items without confirmations 

ex: 
- value: "pls settings confirmations false"

**Comment by Faizan2k7** [comment]
ok thnx
