### ISSUE TITLE
How Can U Ping Someone With An Custom Command Like pls share i dont wanna use the feature since i dont want my main to farm and may get locked

### ISSUE THREAD

**Issue by Catchii** [dankgrinder/dankgrinder#96]
How Can U Ping (Blue Text) Someone With An Custom Command Like pls share i dont wanna use the feature since i dont want my main to farm and may get locked so yea is it possible

**Comment by jotsar** [comment]
`<@userid>`

**Comment by Catchii** [comment]
ty worked

**Comment by Catchii** [comment]
worked ty
